config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/swiss-seismological-service/hermes:
      branch: main
      repo: https://github.com/swiss-seismological-service/hermes
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-magnolia-crab.sh
        container: qc.acc_shaggy-peach-chimpanzee
  QC.Doc:
    repos:
      github.com/swiss-seismological-service/hermes find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cerise-quetzal.sh
        container: qc.doc_flaky-flax-dalmatian
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-denim-dingo.sh
        container: qc.doc_skanky-denim-okapi
      github.com/swiss-seismological-service/hermes markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-dandelion-grouse.sh
        container: qc.doc_flaky-turquoise-reindeer
  QC.Lic:
    repos:
      github.com/swiss-seismological-service/hermes licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-vermilion-fish.sh
        container: qc.lic_bumpy-turquoise-hedgehog
  QC.Sec:
    repos:
      github.com/swiss-seismological-service/hermes bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lemon-monster.sh
        container: qc.sec_scummy-sepia-centipede
  QC.Sty:
    repos:
      github.com/swiss-seismological-service/hermes flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cornflower-mandrill.sh
        container: qc.sty_cranky-magnolia-jackal
      github.com/swiss-seismological-service/hermes hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-blue-discus.sh
        container: qc.sty_stealthy-turquoise-caiman
      github.com/swiss-seismological-service/hermes jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-lemming.sh
        container: qc.sty_snippy-pink-mayfly
  QC.Uni:
    repos:
      github.com/swiss-seismological-service/hermes commands:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-smalt-russel.sh
        container: qc.uni_stealthy-champagne-rattlesnake
  QC.Ver:
    repos:
      github.com/swiss-seismological-service/hermes get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-heliotrope-ocelot.sh
        container: qc.ver_scummy-cream-boar
timeout: 5400
