config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/swiss-seismological-service/hermes:
      branch: v0.2
      repo: https://github.com/swiss-seismological-service/hermes
      subfolder: DTC72/WF7202/ST720202/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-silver-discus.sh
        container: qc.acc_cozy-pear-hippopotamus
  QC.Doc:
    repos:
      github.com/swiss-seismological-service/hermes find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-lilac-mule.sh
        container: qc.doc_snazzy-olive-coyote
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-viridian-crane.sh
        container: qc.doc_flabby-peach-buffalo
      github.com/swiss-seismological-service/hermes markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-orchid-coyote.sh
        container: qc.doc_flimsy-ochre-markhor
  QC.Lic:
    repos:
      github.com/swiss-seismological-service/hermes licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-blue-quail.sh
        container: qc.lic_hazy-indigo-numbat
  QC.Sec:
    repos:
      github.com/swiss-seismological-service/hermes bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-platinum-butterfly.sh
        container: qc.sec_sleepy-emerald-baboon
  QC.Sty:
    repos:
      github.com/swiss-seismological-service/hermes flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-burgundy-javanese.sh
        container: qc.sty_sickly-fuchsia-raccoon
      github.com/swiss-seismological-service/hermes hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-saffron-chow.sh
        container: qc.sty_skimpy-sapphire-alligator
      github.com/swiss-seismological-service/hermes jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-magenta-beaver.sh
        container: qc.sty_stealthy-grey-seal
  QC.Uni:
    repos:
      github.com/swiss-seismological-service/hermes commands:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-amaranth-lion.sh
        container: qc.uni_blurry-bronze-stingray
  QC.Ver:
    repos:
      github.com/swiss-seismological-service/hermes get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-magnolia-hound.sh
        container: qc.ver_lousy-lemon-argentino
timeout: 5400
