config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/swiss-seismological-service/hermes:
      branch: v0.2
      repo: https://github.com/swiss-seismological-service/hermes
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-sepia-devil.sh
        container: qc.acc_whiny-tangerine-fossa
  QC.Doc:
    repos:
      github.com/swiss-seismological-service/hermes find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-rust-cow.sh
        container: qc.doc_sloppy-olive-jellyfish
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-scarlet-havanese.sh
        container: qc.doc_ready-heliotrope-sheep
      github.com/swiss-seismological-service/hermes markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-amethyst-deer.sh
        container: qc.doc_nerdy-lavender-devil
  QC.Lic:
    repos:
      github.com/swiss-seismological-service/hermes licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-heliotrope-booby.sh
        container: qc.lic_frumpy-wheat-russel
  QC.Sec:
    repos:
      github.com/swiss-seismological-service/hermes bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-mustard-quetzal.sh
        container: qc.sec_bumpy-dandelion-gorilla
  QC.Sty:
    repos:
      github.com/swiss-seismological-service/hermes flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-chocolate-leopard.sh
        container: qc.sty_shabby-smalt-havanese
      github.com/swiss-seismological-service/hermes hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-black-bordeaux.sh
        container: qc.sty_leaky-teal-quail
      github.com/swiss-seismological-service/hermes jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olivine-shrimp.sh
        container: qc.sty_pretty-denim-birman
  QC.Uni:
    repos:
      github.com/swiss-seismological-service/hermes commands:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-jade-dunker.sh
        container: qc.uni_leaky-salmon-reindeer
  QC.Ver:
    repos:
      github.com/swiss-seismological-service/hermes get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-sepia-bobcat.sh
        container: qc.ver_crabby-bistre-hedgehog
timeout: 5400
