config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/swiss-seismological-service/hermes:
      branch: main
      repo: https://github.com/swiss-seismological-service/hermes
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-gamboge-uguisu.sh
        container: qc.acc_greasy-white-hornet
  QC.Doc:
    repos:
      github.com/swiss-seismological-service/hermes find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-monster.sh
        container: qc.doc_snippy-russet-wasp
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-razzmatazz-tarantula.sh
        container: qc.doc_fuzzy-magenta-ostrich
      github.com/swiss-seismological-service/hermes markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-pink-cow.sh
        container: qc.doc_homely-rose-snake
  QC.Lic:
    repos:
      github.com/swiss-seismological-service/hermes licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-charcoal-bobcat.sh
        container: qc.lic_stuffy-ultramarine-baboon
  QC.Sec:
    repos:
      github.com/swiss-seismological-service/hermes bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sepia-spitz.sh
        container: qc.sec_bluesy-charcoal-bandicoot
  QC.Sty:
    repos:
      github.com/swiss-seismological-service/hermes flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-pumpkin-fox.sh
        container: qc.sty_crappy-celadon-turkey
      github.com/swiss-seismological-service/hermes hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-turquoise-hyena.sh
        container: qc.sty_craggy-grey-spider
      github.com/swiss-seismological-service/hermes jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ecru-echidna.sh
        container: qc.sty_whiny-khaki-bat
  QC.Uni:
    repos:
      github.com/swiss-seismological-service/hermes commands:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cobalt-paradise.sh
        container: qc.uni_queasy-razzmatazz-emu
  QC.Ver:
    repos:
      github.com/swiss-seismological-service/hermes get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-beige-flamingo.sh
        container: qc.ver_fuzzy-emerald-mayfly
timeout: 5400
