config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/swiss-seismological-service/hermes:
      branch: v0.2
      repo: https://github.com/swiss-seismological-service/hermes
      subfolder: DTC72/WF7202/ST720202/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-gamboge-koala.sh
        container: qc.acc_gummy-linen-fox
  QC.Doc:
    repos:
      github.com/swiss-seismological-service/hermes find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-plum-mule.sh
        container: qc.doc_tasty-linen-catfish
      github.com/swiss-seismological-service/hermes git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-asparagus-zebra.sh
        container: qc.doc_homely-olivine-dhole
      github.com/swiss-seismological-service/hermes markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-teal-goose.sh
        container: qc.doc_wheezy-amaranth-vulture
  QC.Lic:
    repos:
      github.com/swiss-seismological-service/hermes licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-taupe-camel.sh
        container: qc.lic_skanky-orchid-chinook
  QC.Sec:
    repos:
      github.com/swiss-seismological-service/hermes bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-ruby-argentino.sh
        container: qc.sec_freaky-amaranth-shrimp
  QC.Sty:
    repos:
      github.com/swiss-seismological-service/hermes flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-sangria-paradise.sh
        container: qc.sty_cozy-aquamarine-budgerigar
      github.com/swiss-seismological-service/hermes hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ivory-bird.sh
        container: qc.sty_slaphappy-green-tarantula
      github.com/swiss-seismological-service/hermes jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lilac-spoonbill.sh
        container: qc.sty_scanty-orchid-squirt
  QC.Uni:
    repos:
      github.com/swiss-seismological-service/hermes commands:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-indigo-flamingo.sh
        container: qc.uni_leaky-yellow-mastiff
  QC.Ver:
    repos:
      github.com/swiss-seismological-service/hermes get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cobalt-woodlouse.sh
        container: qc.ver_squirrely-charcoal-lizard
timeout: 5400
